spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #url: jdbc:mysql://localhost:3306/task?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://localhost:3306/task?autoReconnect=true&useSSL=false
    username: root
    password:
#配置mapper：
  mybatis:
#    type-aliases-package: day2.demo.test.bean
    mapper-locations: classpath:mapper/*.xml

    # redis
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379
      password:
      jedis:
        pool:
          #最大连接数据库连接数,设 0 为没有限制
          max-active: 8
          #最大等待连接中的数量,设 0 为没有限制
          max-idle: 8
          #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
          max-wait: -1
          #最小等待连接中的数量,设 0 为没有限制
          min-idle: 0
      timeout: 5000
    session:
      store-type: redis
